apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: wisecow
spec:
  secretName: wisecow-tls
  issuerRef:
    name: wisecow-selfsigned
    kind: Issuer
  dnsNames:
    - wisecow.local
